In [16]:
import pandas as pd

In [40]:
db1 = pd.read_csv('weather/3976577.csv')
db2 = pd.read_csv('weather/3976606.csv')
db3 = pd.read_csv('weather/3976607.csv')
db4 = pd.read_csv('weather/3976608.csv')
db5 = pd.read_csv('weather/3976609.csv')
db6 = pd.read_csv('weather/3982396.csv')
db7 = pd.read_csv('weather/3982397.csv')
db8 = pd.read_csv('weather/3982398.csv')
db9 = pd.read_csv('weather/3982400.csv')
db10 = pd.read_csv('weather/3982402.csv')

C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:1: DtypeWarning: Columns (5,6,8,9,10,11,12,13,14,15,16,24,45,47,56,63) have mixed types. Specify dtype option on import or set low_memory=False.
  db1 = pd.read_csv('weather/3976577.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:2: DtypeWarning: Columns (5,6,7,8,9,10,15,46,54) have mixed types. Specify dtype option on import or set low_memory=False.
  db2 = pd.read_csv('weather/3976606.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:3: DtypeWarning: Columns (5,6,7,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  db3 = pd.read_csv('weather/3976607.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:4: DtypeWarning: Columns (4,6,7,9,12,14,15,17,18,19,20,22,23,24,25,33,52,54,55,63,64,71) have mixed types. Specify dtype option on import or set low_memory=False.
  db4 = pd.read_csv('weather/3976608.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:5: DtypeWarning: Columns (23,24,52,54,56,64,65) have mixed types. Specify dtype option on import or set low_memory=False.
  db5 = pd.read_csv('weather/3976609.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:6: DtypeWarning: Columns (45,66,82) have mixed types. Specify dtype option on import or set low_memory=False.
  db6 = pd.read_csv('weather/3982396.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:7: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  db7 = pd.read_csv('weather/3982397.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:8: DtypeWarning: Columns (5,7,8,10,13,29,30,31,34,39,40,45,47,49,69,70,72,73,90,97,98,99,100,101,102,103,104,105,106,107,108,123) have mixed types. Specify dtype option on import or set low_memory=False.
  db8 = pd.read_csv('weather/3982398.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:9: DtypeWarning: Columns (20,25,30,31,36,38,40,60,86,87,88,89,90,91,92,93,94,95,96,97,112) have mixed types. Specify dtype option on import or set low_memory=False.
  db9 = pd.read_csv('weather/3982400.csv')
C:\Users\mpax5\AppData\Local\Temp\ipykernel_10388\1495139166.py:10: DtypeWarning: Columns (38,59,75) have mixed types. Specify dtype option on import or set low_memory=False.
  db10 = pd.read_csv('weather/3982402.csv')

In [19]:
# Length 
print("Length of DB 1 is: ", len(db1)) 
print("Length of DB 2 is: ", len(db2)) 
print("Length of DB 3 is: ", len(db3)) 
print("Length of DB 4 is: ", len(db4)) 
print("Length of DB 5 is: ", len(db5)) 
print("Length of DB 6 is: ", len(db6)) 
print("Length of DB 7 is: ", len(db7)) 
print("Length of DB 8 is: ", len(db8)) 
print("Length of DB 9 is: ", len(db9)) 
print("Length of DB 10 is: ", len(db10))

Length of DB 1 is:  111729
Length of DB 2 is:  94594
Length of DB 3 is:  95129
Length of DB 4 is:  282742
Length of DB 5 is:  91305
Length of DB 6 is:  36951
Length of DB 7 is:  36888
Length of DB 8 is:  73041
Length of DB 9 is:  65871
Length of DB 10 is:  34958

In [22]:
# DB 1 
db1.head(5)

,STATION,DATE,REPORT_TYPE,SOURCE,CoolingDegreeDaysSeasonToDate,DailyAverageDryBulbTemperature,DailyCoolingDegreeDays,DailyDepartureFromNormalAverageTemperature,DailyHeatingDegreeDays,DailyMaximumDryBulbTemperature,...,MonthlyNumberDaysWithThunderstorms,MonthlyTotalLiquidPrecipitation,MonthlyTotalSnowfall,NormalsCoolingDegreeDay,NormalsHeatingDegreeDay,REPORT_TYPE.1,SOURCE.1,Sunrise,Sunset,WindEquipmentChangeDate
0,USW00014739,1950-01-06T00:00:00,SAO,335.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,SAO,335.0,NaN,NaN,10/05/2006
1,USW00014739,1950-01-06T00:00:00,SOD,NaN,NaN,41.0,0.0,10.1,24.0,45.0,...,NaN,NaN,NaN,NaN,NaN,SOD,NaN,714.0,1626.0,10/05/2006
2,USW00014739,1950-01-06T01:00:00,SAO,335.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,SAO,335.0,NaN,NaN,10/05/2006
3,USW00014739,1950-01-06T02:00:00,SAO,335.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,SAO,335.0,NaN,NaN,10/05/2006
4,USW00014739,1950-01-06T03:00:00,SAO,335.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,SAO,335.0,NaN,NaN,10/05/2006

In [42]:
# Rename Station Name 
db1['CITY'] = 'BOSTON'
db1 = db1.drop(columns=['REPORT_TYPE.1', 'SOURCE.1'])

In [44]:
db1 = db1.drop(columns=['WindEquipmentChangeDate'])

In [46]:
db1 = db1.drop(columns=['Sunrise', 'Sunset'])

In [60]:
db1.columns

Index(['DATE', 'MonthlyDepartureFromNormalAverageTemperature',
       'MonthlyDepartureFromNormalCoolingDegreeDays',
       'MonthlyDepartureFromNormalHeatingDegreeDays',
       'MonthlyDepartureFromNormalMaximumTemperature',
       'MonthlyDepartureFromNormalMinimumTemperature',
       'MonthlyDepartureFromNormalPrecipitation', 'MonthlyGreatestPrecip',
       'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth',
       'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall',
       'MonthlyGreatestSnowfallDate', 'MonthlyHeatingDegreeDays',
       'MonthlyMaximumTemperature', 'MonthlyMeanTemperature',
       'MonthlyMinimumTemperature', 'MonthlyNumberDaysWithSnowfall',
       'MonthlyNumberDaysWithThunderstorms', 'MonthlyTotalLiquidPrecipitation',
       'MonthlyTotalSnowfall'],
      dtype='object')

In [50]:
# Include only SOD - Summary of the Day 
db1 = db1[db1['REPORT_TYPE'] == 'SOD']

In [142]:
db1 = db1.drop(columns=['STATION', 'REPORT_TYPE', 'SOURCE',
       'CoolingDegreeDaysSeasonToDate','HeatingDegreeDaysSeasonToDate', 'DailyWeather',
       'HourlyDewPointTemperature', 'HourlyDryBulbTemperature',
       'HourlyPrecipitation', 'HourlyPresentWeatherType',
       'HourlyRelativeHumidity', 'HourlySeaLevelPressure',
       'HourlySkyConditions', 'HourlyStationPressure', 'HourlyVisibility',
       'HourlyWetBulbTemperature', 'HourlyWindDirection', 'HourlyWindSpeed',
       'MonthlyCoolingDegreeDays', 'MonthlyDaysWithGT001Precip',
       'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT32Temp',
       'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT0Temp',
       'MonthlyDaysWithLT32Temp',
       'MonthlyDepartureFromNormalAverageTemperature',
       'MonthlyDepartureFromNormalCoolingDegreeDays',
       'MonthlyDepartureFromNormalHeatingDegreeDays',
       'MonthlyDepartureFromNormalMaximumTemperature',
       'MonthlyDepartureFromNormalMinimumTemperature',
       'MonthlyDepartureFromNormalPrecipitation', 'MonthlyGreatestPrecip',
       'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth',
       'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall',
       'MonthlyGreatestSnowfallDate', 'MonthlyHeatingDegreeDays',
       'MonthlyMaximumTemperature', 'MonthlyMeanTemperature',
       'MonthlyMinimumTemperature', 'MonthlyNumberDaysWithSnowfall',
       'MonthlyNumberDaysWithThunderstorms', 'MonthlyTotalLiquidPrecipitation',
       'MonthlyTotalSnowfall', 'NormalsCoolingDegreeDay',
       'NormalsHeatingDegreeDay'])

In [144]:
db1['DailySnowfall'].dropna()

1        0.0
26         T
51         T
76       0.0
101        T
        ...
98716    0.0
98734    0.0
98752    0.0
98770    0.0
98788    0.0
Name: DailySnowfall, Length: 3744, dtype: object

In [146]:
db1 = db1[db1['DailySnowfall'] != '*']

In [148]:
db1 = db1.dropna(subset=['DailySnowfall'])

In [150]:
db1['DailySnowfall'] = db1['DailySnowfall'].replace('T', '0.005')

In [152]:
db1['DailySnowDepth'] = db1['DailySnowDepth'].replace('T', '0.005')
db1['DailyPrecipitation'] = db1['DailyPrecipitation'].replace('T', '0.005')

In [154]:
db1 = db1.dropna()

In [156]:
# DB2
db2['CITY'] = 'MIAMI'
db2 = db2.drop(columns=['REPORT_TYPE.1', 'SOURCE.1', 'WindEquipmentChangeDate', 'Sunrise', 'Sunset'])
db2 = db2[db2['REPORT_TYPE'] == 'SOD']
db2 = db2.drop(columns=['STATION', 'REPORT_TYPE', 'SOURCE',
       'CoolingDegreeDaysSeasonToDate','HeatingDegreeDaysSeasonToDate',
       'HourlyDewPointTemperature', 'HourlyDryBulbTemperature',
       'HourlyPrecipitation', 'HourlyPresentWeatherType',
       'HourlyRelativeHumidity', 'HourlySeaLevelPressure',
       'HourlySkyConditions', 'HourlyStationPressure', 'HourlyVisibility',
       'HourlyWetBulbTemperature', 'HourlyWindDirection', 'HourlyWindSpeed',
       'MonthlyCoolingDegreeDays', 'MonthlyDaysWithGT001Precip',
       'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT32Temp',
       'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT0Temp',
       'MonthlyDaysWithLT32Temp',
       'MonthlyDepartureFromNormalAverageTemperature',
       'MonthlyDepartureFromNormalCoolingDegreeDays',
       'MonthlyDepartureFromNormalHeatingDegreeDays',
       'MonthlyDepartureFromNormalMaximumTemperature',
       'MonthlyDepartureFromNormalMinimumTemperature',
       'MonthlyDepartureFromNormalPrecipitation', 'MonthlyGreatestPrecip',
       'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth', 'MonthlyHeatingDegreeDays',
       'MonthlyMaximumTemperature', 'MonthlyMeanTemperature',
       'MonthlyMinimumTemperature', 'MonthlyNumberDaysWithSnowfall',
       'MonthlyNumberDaysWithThunderstorms', 'MonthlyGreatestSnowfall', 'MonthlyTotalLiquidPrecipitation',
       'MonthlyTotalSnowfall', 'NormalsCoolingDegreeDay',
       'NormalsHeatingDegreeDay', 'DailyWeather'])
db2.replace('T', 0.005, inplace=True)
db2 = db2.dropna()

In [158]:
db2['DailyPrecipitation'].unique()

array([0.005, '0.00', '0.42', '0.05', '0.02', '0.01', '0.26', '1.03',
       '0.54', '0.09', '0.36', '0.11', '2.36', '0.19', '0.03', '0.66',
       '0.40', '0.04', '0.16', '1.33', '0.18', '0.45', '1.68', '0.87',
       '0.12', '0.39', '1.53', '0.37', '0.34', '0.33', '1.52', '0.72',
       '0.08', '1.50', '0.10', '0.30', '0.53', '0.29', '0.70', '2.08',
       '0.84', '0.97', '0.63', '2.34', '0.51', '0.28', '0.91', '0.22',
       '0.43', '0.24', '0.21', '0.49', '1.07', '1.88', '3.49', '0.92',
       '0.90', '1.74', '0.23', '0.15', '0.65', '0.06', '0.07', '0.35',
       '1.66', '0.95', '0.17', '1.23', '0.46', '2.24', '0.13', '0.71',
       '0.14', '0.79', '2.33', '0.60', '0.27', '0.61', '0.67', '2.78',
       '1.39', '1.00', '0.62', '0.20', '0.56', '1.45', '0.55', '0.50',
       '0.41', '2.95', '1.22', '0.57', '0.99', '0.38', '0.58', '1.36',
       '0.32', '0.74', '4.51', '0.31', '1.02', '0.68', '1.90', '0.25',
       '3.35', '1.06', '3.28', '0.48', '7.88', '1.46', '1.85', '1.30',
       '1.19', '0.75', '1.95', '1.62', '0.69', '1.16', '0.52', '0.77',
       '0.98', '0.82', '1.97', '0.83', '1.01', '2.97', '1.38', '2.43',
       '1.24', '1.09', '1.12', '1.32', '1.99', '2.54', '0.47', '1.40',
       '1.98', '1.44', '2.62', '2.19', '3.94', '2.00', '1.70', '0.59',
       '1.58', '1.26', '3.12', '1.86', '0.78', '1.31', '1.29', '0.94',
       '4.15', '1.54', '3.72', '1.13', '1.25', '1.78', '0.73', '0.85',
       '1.64', '1.04', '0.76', '1.92', '1.83', '1.55', '1.15', '0.86',
       '1.10', '3.42', '1.59', '0.96', '1.49', '2.06', '0.88', '0.64',
       '7.02', '1.20', '1.67', '2.65', '2.66', '2.22', '1.11', '1.72',
       '3.16', '0.44', '2.23', '1.69', '1.35', '2.69', '0.80', '3.93',
       '6.37', '1.65', '1.43', '1.81', '1.87', '1.76', '1.93', '2.13',
       '2.27', '2.09', '5.95', '2.86', '1.84', '0.93', '1.37', '1.05',
       '2.46', '3.45', '0.89', '1.51', '2.45', '1.61', '1.28', '6.78',
       '1.34'], dtype=object)

In [160]:
#DB3 
db3['CITY'] = 'CHICAGO'
db3 = db3[db3['REPORT_TYPE'] == 'SOD']
db3 = db3.drop(columns = ['STATION', 'REPORT_TYPE', 'SOURCE',
       'CoolingDegreeDaysSeasonToDate', 'HeatingDegreeDaysSeasonToDate', 'HourlyDewPointTemperature',
       'HourlyDryBulbTemperature', 'HourlyPrecipitation',
       'HourlyPresentWeatherType', 'HourlyRelativeHumidity',
       'HourlySeaLevelPressure', 'HourlySkyConditions',
       'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature',
       'HourlyWindDirection', 'HourlyWindSpeed', 'MonthlyCoolingDegreeDays',
       'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip',
       'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithGT90Temp',
       'MonthlyDaysWithLT0Temp', 'MonthlyDaysWithLT32Temp',
       'MonthlyGreatestPrecip', 'MonthlyGreatestPrecipDate',
       'MonthlyGreatestSnowDepth', 'MonthlyGreatestSnowfall',
       'MonthlyHeatingDegreeDays', 'MonthlyMaximumTemperature',
       'MonthlyMeanTemperature', 'MonthlyMinimumTemperature',
       'MonthlyNumberDaysWithSnowfall', 'MonthlyTotalLiquidPrecipitation',
       'MonthlyTotalSnowfall', 'REPORT_TYPE.1', 'SOURCE.1', 'Sunrise',
       'Sunset', 'WindEquipmentChangeDate'])
db3.replace('T', 0.005, inplace=True)
db3 = db3.dropna()

In [162]:
db3.head(5)

,DATE,DailyAverageDryBulbTemperature,DailyCoolingDegreeDays,DailyHeatingDegreeDays,DailyMaximumDryBulbTemperature,DailyMinimumDryBulbTemperature,DailyPrecipitation,DailySnowDepth,DailySnowfall,CITY
180,1950-07-01T00:00:00,67,2,0,79,54,0.005,0.0,0.0,CHICAGO
182,1950-07-02T00:00:00,67,2,0,77,57,0.005,0.0,0.0,CHICAGO
183,1950-07-03T00:00:00,68,3,0,75,60,0.03,0.0,0.0,CHICAGO
184,1950-07-04T00:00:00,70,5,0,75,64,0.00,0.0,0.0,CHICAGO
185,1950-07-05T00:00:00,68,3,0,73,62,0.005,0.0,0.0,CHICAGO

In [165]:
# DB4
db4['CITY'] = 'SAN FRANCISCO'
db4 = db4[db4['REPORT_TYPE'] == 'SOD']
db4 = db4.drop(columns = ['STATION', 'REPORT_TYPE', 'SOURCE', 'BackupDirection',
       'BackupDistance', 'BackupDistanceUnit', 'BackupElements',
       'BackupElevation', 'BackupEquipment', 'BackupLatitude', 'DailyPeakWindSpeed',
        'DailyPeakWindDirection',                  
       'BackupLongitude', 'BackupName', 'CoolingDegreeDaysSeasonToDate', 'DailyWeather',
       'HeatingDegreeDaysSeasonToDate', 'HourlyDewPointTemperature',
       'HourlyDryBulbTemperature', 'HourlyPrecipitation',
       'HourlyPresentWeatherType', 'HourlyRelativeHumidity',
       'HourlySeaLevelPressure', 'HourlySkyConditions',
       'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature',
       'HourlyWindDirection', 'HourlyWindSpeed', 'MonthlyCoolingDegreeDays',
       'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip',
       'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithGT90Temp',
       'MonthlyDaysWithLT0Temp', 'MonthlyDaysWithLT32Temp',
       'MonthlyDepartureFromNormalAverageTemperature',
       'MonthlyDepartureFromNormalCoolingDegreeDays',
       'MonthlyDepartureFromNormalHeatingDegreeDays',
       'MonthlyDepartureFromNormalMaximumTemperature',
       'MonthlyDepartureFromNormalMinimumTemperature',
       'MonthlyDepartureFromNormalPrecipitation', 'MonthlyGreatestPrecip',
       'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth',
       'MonthlyGreatestSnowfall', 'MonthlyGreatestSnowfallDate',
       'MonthlyHeatingDegreeDays', 'MonthlyMaximumTemperature',
       'MonthlyMeanTemperature', 'MonthlyMinimumTemperature',
       'MonthlyNumberDaysWithSnowfall', 'MonthlyNumberDaysWithThunderstorms',
       'MonthlyTotalLiquidPrecipitation', 'MonthlyTotalSnowfall',
       'NormalsCoolingDegreeDay', 'NormalsHeatingDegreeDay', 'REPORT_TYPE.1',
       'SOURCE.1', 'Sunrise', 'Sunset', 'WindEquipmentChangeDate'])
db4.replace('T', 0.005, inplace=True)
db4 = db4.dropna()

In [167]:
# DB5

In [169]:
db5['CITY'] = 'WINSLOW'
db5 = db5[db5['REPORT_TYPE'] == 'SOD']
db5 = db5.drop(columns = ['STATION', 'REPORT_TYPE', 'SOURCE', 'BackupDirection',
       'BackupDistance', 'BackupDistanceUnit', 'BackupElements',
       'BackupElevation', 'BackupEquipment', 'BackupLatitude',
       'BackupLongitude', 'BackupName', 'CoolingDegreeDaysSeasonToDate',
       'DailyAverageDryBulbTemperature', 'DailyWeather', 'DailyPeakWindDirection',
       'DailyPeakWindSpeed',
       'HeatingDegreeDaysSeasonToDate', 'HourlyDewPointTemperature',
       'HourlyDryBulbTemperature', 'HourlyPrecipitation',
       'HourlyPresentWeatherType', 'HourlyRelativeHumidity',
       'HourlySeaLevelPressure', 'HourlySkyConditions',
       'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature',
       'HourlyWindDirection', 'HourlyWindSpeed', 'MonthlyCoolingDegreeDays',
       'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip',
       'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithGT90Temp',
       'MonthlyDaysWithLT0Temp', 'MonthlyDaysWithLT32Temp',
       'MonthlyDepartureFromNormalAverageTemperature',
       'MonthlyDepartureFromNormalCoolingDegreeDays',
       'MonthlyDepartureFromNormalHeatingDegreeDays',
       'MonthlyDepartureFromNormalMaximumTemperature',
       'MonthlyDepartureFromNormalMinimumTemperature',
       'MonthlyDepartureFromNormalPrecipitation', 'MonthlyGreatestPrecip',
       'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth',
       'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall',
       'MonthlyGreatestSnowfallDate', 'MonthlyHeatingDegreeDays',
       'MonthlyMaximumTemperature', 'MonthlyMeanTemperature',
       'MonthlyMinimumTemperature', 'MonthlyNumberDaysWithSnowfall',
       'MonthlyNumberDaysWithThunderstorms', 'MonthlyTotalLiquidPrecipitation',
       'MonthlyTotalSnowfall', 'NormalsCoolingDegreeDay',
       'NormalsHeatingDegreeDay', 'REPORT_TYPE.1', 'SOURCE.1', 'Sunrise',
       'Sunset', 'WindEquipmentChangeDate'])
db5.replace('T', 0.005, inplace=True)
db5 = db5.dropna()

# Merge

In [172]:
# Merge 
dfs = [db1, db2, db3, db4, db5] 
merged_df = pd.concat(dfs, ignore_index=True)

In [174]:
len(merged_df)

18343

In [176]:
merged_df.fillna(0, inplace=True)

In [178]:
columns_numeric = ['DailyAverageDryBulbTemperature', 'DailyCoolingDegreeDays',
       'DailyDepartureFromNormalAverageTemperature', 'DailyHeatingDegreeDays',
       'DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature',
       'DailyPeakWindDirection', 'DailyPeakWindSpeed', 'DailyPrecipitation',
       'DailySnowDepth', 'DailySnowfall']

for col in columns_numeric: 
    merged_df = merged_df[merged_df[col] != '*']
    merged_df[col] = pd.to_numeric(merged_df[col])

In [180]:
temp = merged_df[merged_df['CITY'] == 'MIAMI']
temp['DailyPrecipitation']

3616    0.005
3617    0.005
3618    0.005
3619    0.005
3620    0.005
        ...
7257    0.110
7258    0.010
7259    0.000
7260    0.000
7261    0.000
Name: DailyPrecipitation, Length: 3646, dtype: float64

In [182]:
merged_df.to_csv('weather_train.csv')

# Test

In [185]:
db6['CITY'] = 'SAN FRANCISCO'
db6 = db6[db6['REPORT_TYPE'] == 'SOD']
db6 = db6.drop(columns = ['STATION',
 'NAME',
 'REPORT_TYPE',
 'SOURCE',
 'BackupDirection',
 'BackupDistance',
 'BackupDistanceUnit',
 'BackupElements',
 'BackupElevation',
 'BackupEquipment',
 'BackupLatitude',
 'BackupLongitude',
 'BackupName',
 'CoolingDegreeDaysSeasonToDate',
 'DailyWeather',
 'HeatingDegreeDaysSeasonToDate',
 'HourlyAltimeterSetting',
 'HourlyDewPointTemperature',
 'HourlyDryBulbTemperature',
 'HourlyPrecipitation',
 'HourlyPresentWeatherType',
 'HourlyPressureChange',
 'HourlyPressureTendency',
 'HourlyRelativeHumidity',
 'HourlySeaLevelPressure',
 'HourlySkyConditions',
 'HourlyStationPressure',
 'HourlyVisibility',
 'HourlyWetBulbTemperature',
 'HourlyWindDirection',
 'HourlyWindGustSpeed',
 'HourlyWindSpeed',
 'MonthlyAverageRH',
 'MonthlyAverageWindSpeed',
 'MonthlyCoolingDegreeDays',
 'MonthlyDaysWithGT001Precip',
 'MonthlyDaysWithGT010Precip',
 'MonthlyDaysWithGT32Temp',
 'MonthlyDaysWithGT90Temp',
 'MonthlyDaysWithLT0Temp',
 'MonthlyDaysWithLT32Temp',
 'MonthlyDepartureFromNormalAverageTemperature',
 'MonthlyDepartureFromNormalCoolingDegreeDays',
 'MonthlyDepartureFromNormalHeatingDegreeDays',
 'MonthlyDepartureFromNormalMaximumTemperature',
 'MonthlyDepartureFromNormalMinimumTemperature',
 'MonthlyDepartureFromNormalPrecipitation',
 'MonthlyDewpointTemperature',
 'MonthlyGreatestPrecip',
 'MonthlyGreatestPrecipDate',
 'MonthlyHeatingDegreeDays',
 'MonthlyMaxSeaLevelPressureValue',
 'MonthlyMaxSeaLevelPressureValueDate',
 'MonthlyMaxSeaLevelPressureValueTime',
 'MonthlyMaximumTemperature',
 'MonthlyMeanTemperature',
 'MonthlyMinSeaLevelPressureValue',
 'MonthlyMinSeaLevelPressureValueDate',
 'MonthlyMinSeaLevelPressureValueTime',
 'MonthlyMinimumTemperature',
 'MonthlyNumberDaysWithHeavyFog',
 'MonthlyNumberDaysWithThunderstorms',
 'MonthlySeaLevelPressure',
 'MonthlyStationPressure',
 'MonthlyTotalLiquidPrecipitation',
 'MonthlyWetBulb',
 'NormalsCoolingDegreeDay',
 'NormalsHeatingDegreeDay',
 'REM',
 'REPORT_TYPE.1',
 'SOURCE.1',
 'ShortDurationEndDate005',
 'ShortDurationEndDate010',
 'ShortDurationEndDate015',
 'ShortDurationEndDate020',
 'ShortDurationEndDate030',
 'ShortDurationEndDate045',
 'ShortDurationEndDate060',
 'ShortDurationEndDate080',
 'ShortDurationEndDate100',
 'ShortDurationEndDate120',
 'ShortDurationEndDate150',
 'ShortDurationEndDate180',
 'ShortDurationPrecipitationValue005',
 'ShortDurationPrecipitationValue010',
 'ShortDurationPrecipitationValue015',
 'ShortDurationPrecipitationValue020',
 'ShortDurationPrecipitationValue030',
 'ShortDurationPrecipitationValue045',
 'ShortDurationPrecipitationValue060',
 'ShortDurationPrecipitationValue080',
 'ShortDurationPrecipitationValue100',
 'ShortDurationPrecipitationValue120',
 'ShortDurationPrecipitationValue150',
 'ShortDurationPrecipitationValue180',
 'Sunrise',
 'Sunset',
 'WindEquipmentChangeDate'])
db6.replace('T', 0.005, inplace=True)
db6 = db6.dropna()

In [187]:
db7['CITY'] = 'CHICAGO'
db7 = db7[db7['REPORT_TYPE'] == 'SOD']
db7 = db7.drop(columns = ['STATION',
 'REPORT_TYPE',
 'SOURCE',
 'CoolingDegreeDaysSeasonToDate',
 'DailyWeather',
 'HeatingDegreeDaysSeasonToDate',
 'HourlyAltimeterSetting',
 'HourlyDewPointTemperature',
 'HourlyDryBulbTemperature',
 'HourlyPrecipitation',
 'HourlyPresentWeatherType',
 'HourlyPressureChange',
 'HourlyPressureTendency',
 'HourlyRelativeHumidity',
 'HourlySeaLevelPressure',
 'HourlySkyConditions',
 'HourlyStationPressure',
 'HourlyVisibility',
 'HourlyWetBulbTemperature',
 'HourlyWindDirection',
 'HourlyWindGustSpeed',
 'HourlyWindSpeed',
 'MonthlyAverageWindSpeed',
 'MonthlyCoolingDegreeDays',
 'MonthlyDaysWithGT001Precip',
 'MonthlyDaysWithGT010Precip',
 'MonthlyDaysWithGT32Temp',
 'MonthlyDaysWithGT90Temp',
 'MonthlyDaysWithLT0Temp',
 'MonthlyDaysWithLT32Temp',
 'MonthlyDepartureFromNormalAverageTemperature',
 'MonthlyDepartureFromNormalCoolingDegreeDays',
 'MonthlyDepartureFromNormalHeatingDegreeDays',
 'MonthlyDepartureFromNormalMaximumTemperature',
 'MonthlyDepartureFromNormalMinimumTemperature',
 'MonthlyDepartureFromNormalPrecipitation',
 'MonthlyGreatestPrecip',
 'MonthlyGreatestPrecipDate',
 'MonthlyGreatestSnowDepth',
 'MonthlyGreatestSnowDepthDate',
 'MonthlyHeatingDegreeDays',
 'MonthlyMaxSeaLevelPressureValue',
 'MonthlyMaxSeaLevelPressureValueDate',
 'MonthlyMaxSeaLevelPressureValueTime',
 'MonthlyMaximumTemperature',
 'MonthlyMeanTemperature',
 'MonthlyMinSeaLevelPressureValue',
 'MonthlyMinSeaLevelPressureValueDate',
 'MonthlyMinSeaLevelPressureValueTime',
 'MonthlyMinimumTemperature',
 'MonthlyNumberDaysWithHeavyFog',
 'MonthlyNumberDaysWithThunderstorms',
 'MonthlyTotalLiquidPrecipitation',
 'NormalsCoolingDegreeDay',
 'NormalsHeatingDegreeDay',
 'REM',
 'REPORT_TYPE.1',
 'SOURCE.1',
 'ShortDurationEndDate005',
 'ShortDurationEndDate010',
 'ShortDurationEndDate015',
 'ShortDurationEndDate020',
 'ShortDurationEndDate030',
 'ShortDurationEndDate045',
 'ShortDurationEndDate060',
 'ShortDurationEndDate080',
 'ShortDurationEndDate100',
 'ShortDurationEndDate120',
 'ShortDurationEndDate150',
 'ShortDurationEndDate180',
 'ShortDurationPrecipitationValue005',
 'ShortDurationPrecipitationValue010',
 'ShortDurationPrecipitationValue015',
 'ShortDurationPrecipitationValue020',
 'ShortDurationPrecipitationValue030',
 'ShortDurationPrecipitationValue045',
 'ShortDurationPrecipitationValue060',
 'ShortDurationPrecipitationValue080',
 'ShortDurationPrecipitationValue100',
 'ShortDurationPrecipitationValue120',
 'ShortDurationPrecipitationValue150',
 'ShortDurationPrecipitationValue180',
 'Sunrise',
 'Sunset',
 'WindEquipmentChangeDate'])
db7.replace('T', 0.005, inplace=True)
db7 = db7.dropna()

In [216]:
db7.columns

Index(['DATE', 'DailyAverageDryBulbTemperature', 'DailyAverageWindSpeed',
       'DailyCoolingDegreeDays', 'DailyDepartureFromNormalAverageTemperature',
       'DailyHeatingDegreeDays', 'DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindDirection',
       'DailyPeakWindSpeed', 'DailyPrecipitation', 'DailySnowDepth',
       'DailySustainedWindDirection', 'DailySustainedWindSpeed', 'CITY'],
      dtype='object')

In [218]:
db7['DailySnowDepth'].unique()

array([2., 1., 0., 3., 4., 8., 7., 5., 6.])

In [191]:
db8['CITY'] = 'BOSTON'
db8 = db8[db8['REPORT_TYPE'] == 'SOD']
db8 = db8.drop(columns = ['STATION',
 'NAME',
 'REPORT_TYPE',
 'SOURCE',
 'BackupDirection',
 'BackupDistance',
 'BackupDistanceUnit',
 'BackupElements',
 'BackupElevation',
 'BackupEquipment',
 'BackupLatitude',
 'BackupLongitude',
 'BackupName',
 'CoolingDegreeDaysSeasonToDate',
 'DailyWeather',
 'HeatingDegreeDaysSeasonToDate',
 'HourlyAltimeterSetting',
 'HourlyDewPointTemperature',
 'HourlyDryBulbTemperature',
 'HourlyPrecipitation',
 'HourlyPresentWeatherType',
 'HourlyPressureChange',
 'HourlyPressureTendency',
 'HourlyRelativeHumidity',
 'HourlySeaLevelPressure',
 'HourlySkyConditions',
 'HourlyStationPressure',
 'HourlyVisibility',
 'HourlyWetBulbTemperature',
 'HourlyWindDirection',
 'HourlyWindGustSpeed',
 'HourlyWindSpeed',
 'MonthlyAverageRH',
 'MonthlyAverageWindSpeed',
 'MonthlyCoolingDegreeDays',
 'MonthlyDaysWithGT001Precip',
 'MonthlyDaysWithGT010Precip',
 'MonthlyDaysWithGT32Temp',
 'MonthlyDaysWithGT90Temp',
 'MonthlyDaysWithLT0Temp',
 'MonthlyDaysWithLT32Temp',
 'MonthlyDepartureFromNormalAverageTemperature',
 'MonthlyDepartureFromNormalCoolingDegreeDays',
 'MonthlyDepartureFromNormalHeatingDegreeDays',
 'MonthlyDepartureFromNormalMaximumTemperature',
 'MonthlyDepartureFromNormalMinimumTemperature',
 'MonthlyDepartureFromNormalPrecipitation',
 'MonthlyDewpointTemperature',
 'MonthlyGreatestPrecip',
 'MonthlyGreatestPrecipDate',
 'MonthlyGreatestSnowDepth',
 'MonthlyGreatestSnowDepthDate',
 'MonthlyGreatestSnowfall',
 'MonthlyGreatestSnowfallDate',
 'MonthlyHeatingDegreeDays',
 'MonthlyMaxSeaLevelPressureValue',
 'MonthlyMaxSeaLevelPressureValueDate',
 'MonthlyMaxSeaLevelPressureValueTime',
 'MonthlyMaximumTemperature',
 'MonthlyMeanTemperature',
 'MonthlyMinSeaLevelPressureValue',
 'MonthlyMinSeaLevelPressureValueDate',
 'MonthlyMinSeaLevelPressureValueTime',
 'MonthlyMinimumTemperature',
 'MonthlyNumberDaysWithHeavyFog',
 'MonthlyNumberDaysWithSnowfall',
 'MonthlyNumberDaysWithThunderstorms',
 'MonthlySeaLevelPressure',
 'MonthlyStationPressure',
 'MonthlyTotalLiquidPrecipitation',
 'MonthlyTotalSnowfall',
 'MonthlyWetBulb',
 'NormalsCoolingDegreeDay',
 'NormalsHeatingDegreeDay',
 'REM',
 'REPORT_TYPE.1',
 'SOURCE.1',
 'ShortDurationEndDate005',
 'ShortDurationEndDate010',
 'ShortDurationEndDate015',
 'ShortDurationEndDate020',
 'ShortDurationEndDate030',
 'ShortDurationEndDate045',
 'ShortDurationEndDate060',
 'ShortDurationEndDate080',
 'ShortDurationEndDate100',
 'ShortDurationEndDate120',
 'ShortDurationEndDate150',
 'ShortDurationEndDate180',
 'ShortDurationPrecipitationValue005',
 'ShortDurationPrecipitationValue010',
 'ShortDurationPrecipitationValue015',
 'ShortDurationPrecipitationValue020',
 'ShortDurationPrecipitationValue030',
 'ShortDurationPrecipitationValue045',
 'ShortDurationPrecipitationValue060',
 'ShortDurationPrecipitationValue080',
 'ShortDurationPrecipitationValue100',
 'ShortDurationPrecipitationValue120',
 'ShortDurationPrecipitationValue150',
 'ShortDurationPrecipitationValue180',
 'Sunrise',
 'Sunset',
 'WindEquipmentChangeDate'])
db8.replace('T', 0.005, inplace=True)
db8.fillna(0, inplace=True)

In [193]:
db9['CITY'] = 'MIAMI'
db9 = db9[db9['REPORT_TYPE'] == 'SOD']
db9 = db9.drop(columns = ['STATION',
 'NAME',
 'REPORT_TYPE',
 'SOURCE',
 'CoolingDegreeDaysSeasonToDate',
 'DailyWeather',
 'HeatingDegreeDaysSeasonToDate',
 'HourlyAltimeterSetting',
 'HourlyDewPointTemperature',
 'HourlyDryBulbTemperature',
 'HourlyPrecipitation',
 'HourlyPresentWeatherType',
 'HourlyPressureChange',
 'HourlyPressureTendency',
 'HourlyRelativeHumidity',
 'HourlySeaLevelPressure',
 'HourlySkyConditions',
 'HourlyStationPressure',
 'HourlyVisibility',
 'HourlyWetBulbTemperature',
 'HourlyWindDirection',
 'HourlyWindGustSpeed',
 'HourlyWindSpeed',
 'MonthlyAverageRH',
 'MonthlyAverageWindSpeed',
 'MonthlyCoolingDegreeDays',
 'MonthlyDaysWithGT001Precip',
 'MonthlyDaysWithGT010Precip',
 'MonthlyDaysWithGT32Temp',
 'MonthlyDaysWithGT90Temp',
 'MonthlyDaysWithLT0Temp',
 'MonthlyDaysWithLT32Temp',
 'MonthlyDepartureFromNormalAverageTemperature',
 'MonthlyDepartureFromNormalCoolingDegreeDays',
 'MonthlyDepartureFromNormalHeatingDegreeDays',
 'MonthlyDepartureFromNormalMaximumTemperature',
 'MonthlyDepartureFromNormalMinimumTemperature',
 'MonthlyDepartureFromNormalPrecipitation',
 'MonthlyDewpointTemperature',
 'MonthlyGreatestPrecip',
 'MonthlyGreatestPrecipDate',
 'MonthlyGreatestSnowDepth',
 'MonthlyGreatestSnowfall',
 'MonthlyHeatingDegreeDays',
 'MonthlyMaxSeaLevelPressureValue',
 'MonthlyMaxSeaLevelPressureValueDate',
 'MonthlyMaxSeaLevelPressureValueTime',
 'MonthlyMaximumTemperature',
 'MonthlyMeanTemperature',
 'MonthlyMinSeaLevelPressureValue',
 'MonthlyMinSeaLevelPressureValueDate',
 'MonthlyMinSeaLevelPressureValueTime',
 'MonthlyMinimumTemperature',
 'MonthlyNumberDaysWithHeavyFog',
 'MonthlyNumberDaysWithSnowfall',
 'MonthlyNumberDaysWithThunderstorms',
 'MonthlySeaLevelPressure',
 'MonthlyStationPressure',
 'MonthlyTotalLiquidPrecipitation',
 'MonthlyTotalSnowfall',
 'MonthlyWetBulb',
 'NormalsCoolingDegreeDay',
 'NormalsHeatingDegreeDay',
 'REM',
 'REPORT_TYPE.1',
 'SOURCE.1',
 'ShortDurationEndDate005',
 'ShortDurationEndDate010',
 'ShortDurationEndDate015',
 'ShortDurationEndDate020',
 'ShortDurationEndDate030',
 'ShortDurationEndDate045',
 'ShortDurationEndDate060',
 'ShortDurationEndDate080',
 'ShortDurationEndDate100',
 'ShortDurationEndDate120',
 'ShortDurationEndDate150',
 'ShortDurationEndDate180',
 'ShortDurationPrecipitationValue005',
 'ShortDurationPrecipitationValue010',
 'ShortDurationPrecipitationValue015',
 'ShortDurationPrecipitationValue020',
 'ShortDurationPrecipitationValue030',
 'ShortDurationPrecipitationValue045',
 'ShortDurationPrecipitationValue060',
 'ShortDurationPrecipitationValue080',
 'ShortDurationPrecipitationValue100',
 'ShortDurationPrecipitationValue120',
 'ShortDurationPrecipitationValue150',
 'ShortDurationPrecipitationValue180',
 'Sunrise',
 'Sunset',
 'WindEquipmentChangeDate'])
db9.replace('T', 0.005, inplace=True)
db9 = db9.dropna()

In [203]:
db10['CITY'] = 'WINSLOW'
db10 = db10[db10['REPORT_TYPE'] == 'SOD']
db10 = db10.drop(columns =['STATION',
 'NAME',
 'REPORT_TYPE',
 'SOURCE',
 'CoolingDegreeDaysSeasonToDate',
 'DailyWeather',
 'HeatingDegreeDaysSeasonToDate',
 'HourlyAltimeterSetting',
 'HourlyDewPointTemperature',
 'HourlyDryBulbTemperature',
 'HourlyPrecipitation',
 'HourlyPresentWeatherType',
 'HourlyPressureChange',
 'HourlyPressureTendency',
 'HourlyRelativeHumidity',
 'HourlySeaLevelPressure',
 'HourlySkyConditions',
 'HourlyStationPressure',
 'HourlyVisibility',
 'HourlyWetBulbTemperature',
 'HourlyWindDirection',
 'HourlyWindGustSpeed',
 'HourlyWindSpeed',
 'MonthlyAverageRH',
 'MonthlyAverageWindSpeed',
 'MonthlyCoolingDegreeDays',
 'MonthlyDaysWithGT001Precip',
 'MonthlyDaysWithGT010Precip',
 'MonthlyDaysWithGT32Temp',
 'MonthlyDaysWithGT90Temp',
 'MonthlyDaysWithLT0Temp',
 'MonthlyDaysWithLT32Temp',
 'MonthlyDepartureFromNormalAverageTemperature',
 'MonthlyDepartureFromNormalCoolingDegreeDays',
 'MonthlyDepartureFromNormalHeatingDegreeDays',
 'MonthlyDepartureFromNormalMaximumTemperature',
 'MonthlyDepartureFromNormalMinimumTemperature',
 'MonthlyDepartureFromNormalPrecipitation',
 'MonthlyDewpointTemperature',
 'MonthlyGreatestPrecip',
 'MonthlyGreatestPrecipDate',
 'MonthlyHeatingDegreeDays',
 'MonthlyMaxSeaLevelPressureValue',
 'MonthlyMaxSeaLevelPressureValueDate',
 'MonthlyMaxSeaLevelPressureValueTime',
 'MonthlyMaximumTemperature',
 'MonthlyMeanTemperature',
 'MonthlyMinSeaLevelPressureValue',
 'MonthlyMinSeaLevelPressureValueDate',
 'MonthlyMinSeaLevelPressureValueTime',
 'MonthlyMinimumTemperature',
 'MonthlyNumberDaysWithHeavyFog',
 'MonthlyNumberDaysWithThunderstorms',
 'MonthlySeaLevelPressure',
 'MonthlyStationPressure',
 'MonthlyTotalLiquidPrecipitation',
 'MonthlyWetBulb',
 'NormalsCoolingDegreeDay',
 'NormalsHeatingDegreeDay',
 'REM',
 'REPORT_TYPE.1',
 'SOURCE.1',
 'ShortDurationEndDate005',
 'ShortDurationEndDate010',
 'ShortDurationEndDate015',
 'ShortDurationEndDate020',
 'ShortDurationEndDate030',
 'ShortDurationEndDate045',
 'ShortDurationEndDate060',
 'ShortDurationEndDate080',
 'ShortDurationEndDate100',
 'ShortDurationEndDate120',
 'ShortDurationEndDate150',
 'ShortDurationEndDate180',
 'ShortDurationPrecipitationValue005',
 'ShortDurationPrecipitationValue010',
 'ShortDurationPrecipitationValue015',
 'ShortDurationPrecipitationValue020',
 'ShortDurationPrecipitationValue030',
 'ShortDurationPrecipitationValue045',
 'ShortDurationPrecipitationValue060',
 'ShortDurationPrecipitationValue080',
 'ShortDurationPrecipitationValue100',
 'ShortDurationPrecipitationValue120',
 'ShortDurationPrecipitationValue150',
 'ShortDurationPrecipitationValue180',
 'Sunrise',
 'Sunset',
 'WindEquipmentChangeDate']) 
db10.replace('T', 0.005, inplace=True)
db10.fillna(0, inplace=True)

# Merge

In [206]:
dfs = [db6, db7, db8, db9, db10] 
merged_df = pd.concat(dfs, ignore_index=True)

In [208]:
merged_df.columns

Index(['DATE', 'DailyAverageDewPointTemperature',
       'DailyAverageDryBulbTemperature', 'DailyAverageRelativeHumidity',
       'DailyAverageSeaLevelPressure', 'DailyAverageStationPressure',
       'DailyAverageWetBulbTemperature', 'DailyAverageWindSpeed',
       'DailyCoolingDegreeDays', 'DailyDepartureFromNormalAverageTemperature',
       'DailyHeatingDegreeDays', 'DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindDirection',
       'DailyPeakWindSpeed', 'DailyPrecipitation',
       'DailySustainedWindDirection', 'DailySustainedWindSpeed', 'CITY',
       'DailySnowDepth', 'DailySnowfall'],
      dtype='object')

In [210]:
merged_df.fillna(0, inplace=True)
columns_numeric = ['DailyAverageDewPointTemperature',
       'DailyAverageDryBulbTemperature', 'DailyAverageRelativeHumidity',
       'DailyAverageSeaLevelPressure', 'DailyAverageStationPressure',
       'DailyAverageWetBulbTemperature', 'DailyAverageWindSpeed',
       'DailyCoolingDegreeDays', 'DailyDepartureFromNormalAverageTemperature',
       'DailyHeatingDegreeDays', 'DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindDirection',
       'DailyPeakWindSpeed', 'DailyPrecipitation',
       'DailySustainedWindDirection', 'DailySustainedWindSpeed',
       'DailySnowDepth', 'DailySnowfall']

for col in columns_numeric: 
    merged_df = merged_df[merged_df[col] != '*']
    merged_df[col] = pd.to_numeric(merged_df[col])

In [212]:
merged_df.to_csv('weather_test.csv')